### PR TITLE
Update license with latest GPLv2 copy from gnu.org

### PR DESCRIPTION
**Pull request by morxa**
Use the latest version from
https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

In particular, update the address of the Free Software Foundation.

### CODE REVIEW

**Comment by morxa** [comment]
The wrong address was found by an automatic check by the Fedora packaging machinery: https://taskotron.fedoraproject.org/artifacts/all/5630cc20-7893-11e8-b93a-525400fc9f92/tests.yml/bibtex2html-1.99-1.fc28.log

**Comment by morxa** [comment]
What's the status here? Is there a reason not to merge this?

**Comment by backtracking** [comment]
No good reason, apart from myself doing too many things already.
Thanks for the patch.

**Comment by morxa** [comment]
Thanks for merging!

**Pull request merged**
